### ISSUE TITLE
 Exception: The CiviCRM Api3 call return value is empty

### ISSUE THREAD

**Issue by jamjon3** [leanwebstart/civi-api3#2]
Thank you for writing this (I had been struggling to get json working). I'm using v1.0.5.

When I try test this call:

`$api->Contact->Get(2)`

I get the stated exception above (_Note: ID 2 exists_)

I have these keys (obscuring key values) set in .env

```
CIVI_HOST=http://www.example.org
CIVI_INTEGRATION=wordpress
CIVI_SITE_KEY=<secret>
CIVI_USER_KEY=<secret>
```
I know my site and user keys are valid. They work in Postman as long as I set json=1. Any thoughts? Thank you in advance!

**Comment by jamjon3** [comment]
FYI: I did run `php artisan vendor:publish` and selected your package to create the `config/civi-api3.php` file.

**Comment by leanwebstart** [comment]
Hmm... That comes from AbstractAPI.php... fromt his function... 

` protected function checkResult($result, $entity, $action, $params)
    {
        if (empty($result) || !is_object($result)) {
            throw new \Exception("The CiviCRM Api3 call return value is empty");
        } elseif (!empty($result->is_error)) {
            $msg = !empty($result->error_message) ? "CiviCRM Api3 error: " . $result->error_message : "CiviCRM Api3 returned an unknown error";
            throw new \Exception($msg);
        } else {
            return $result;
        }
    }`

What happens if you do dd($result) before the first if... Wondering what is returned ...

**Comment by jamjon3** [comment]
After adding `dd($result)`, I'm getting `null` from it. I'll poke around and check a few more things and let you know. Thank you!

**Comment by jamjon3** [comment]
Still 'poking' around but I noticed the queryString getting produced looks like this for the 'action':
entity=Contact&action=Get&key=
But in CiviCRM API explorer, I'm seeing that as in lowercase format
entity=Contact&action=get
That didn't fix the issue when I changed the case though...

I set that in EntityAPI.php via lcfirst...
```
    public function __call($action, $args)
    {
        return $this->api->call($this->entity, lcfirst($action), $args[0]);
    }
```

**Comment by jamjon3** [comment]
The 'raw' response from PHP curl looks like this (before the json_decode on method apiCall on CiviAPI.php):

"""
<!DOCTYPE html>\n
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">\n
<head>\n
\t<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n
\t<meta name="viewport" content="width=device-width">\n
\t<meta name='robots' content='noindex,follow' />\n
\t<title>WordPress &rsaquo; Error</title>\n
\t<style type="text/css">\n
\t\thtml {\n
\t\t\tbackground: #f1f1f1;\n
\t\t}\n
\t\tbody {\n
\t\t\tbackground: #fff;\n
\t\t\tcolor: #444;\n
\t\t\tfont-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;\n
\t\t\tmargin: 2em auto;\n
\t\t\tpadding: 1em 2em;\n
\t\t\tmax-width: 700px;\n
\t\t\t-webkit-box-shadow: 0 1px 3px rgba(0,0,0,0.13);\n
\t\t\tbox-shadow: 0 1px 3px rgba(0,0,0,0.13);\n
\t\t}\n
\t\th1 {\n
\t\t\tborder-bottom: 1px solid #dadada;\n
\t\t\tclear: both;\n
\t\t\tcolor: #666;\n
\t\t\tfont-size: 24px;\n
\t\t\tmargin: 30px 0 0 0;\n
\t\t\tpadding: 0;\n
\t\t\tpadding-bottom: 7px;\n
\t\t}\n
\t\t#error-page {\n
\t\t\tmargin-top: 50px;\n
\t\t}\n
\t\t#error-page p {\n
\t\t\tfont-size: 14px;\n
\t\t\tline-height: 1.5;\n
\t\t\tmargin: 25px 0 20px;\n
\t\t}\n
\t\t#error-page code {\n
\t\t\tfont-family: Consolas, Monaco, monospace;\n
\t\t}\n
\t\tul li {\n
\t\t\tmargin-bottom: 10px;\n
\t\t\tfont-size: 14px ;\n
\t\t}\n
\t\ta {\n
\t\t\tcolor: #0073aa;\n
\t\t}\n
\t\ta:hover,\n
\t\ta:active {\n
\t\t\tcolor: #00a0d2;\n
\t\t}\n
\t\ta:focus {\n
\t\t\tcolor: #124964;\n
\t\t    -webkit-box-shadow:\n
\t\t    \t0 0 0 1px #5b9dd9,\n
\t\t\t\t0 0 2px 1px rgba(30, 140, 190, .8);\n
\t\t    box-shadow:\n
\t\t    \t0 0 0 1px #5b9dd9,\n
\t\t\t\t0 0 2px 1px rgba(30, 140, 190, .8);\n
\t\t\toutline: none;\n
\t\t}\n
\t\t.button {\n
\t\t\tbackground: #f7f7f7;\n
\t\t\tborder: 1px solid #ccc;\n
\t\t\tcolor: #555;\n
\t\t\tdisplay: inline-block;\n
\t\t\ttext-decoration: none;\n
\t\t\tfont-size: 13px;\n
\t\t\tline-height: 26px;\n
\t\t\theight: 28px;\n
\t\t\tmargin: 0;\n
\t\t\tpadding: 0 10px 1px;\n
\t\t\tcursor: pointer;\n
\t\t\t-webkit-border-radius: 3px;\n
\t\t\t-webkit-appearance: none;\n
\t\t\tborder-radius: 3px;\n
\t\t\twhite-space: nowrap;\n
\t\t\t-webkit-box-sizing: border-box;\n
\t\t\t-moz-box-sizing:    border-box;\n
\t\t\tbox-sizing:         border-box;\n
\n
\t\t\t-webkit-box-shadow: 0 1px 0 #ccc;\n
\t\t\tbox-shadow: 0 1px 0 #ccc;\n
\t\t \tvertical-align: top;\n
\t\t}\n
\n
\t\t.button.button-large {\n
\t\t\theight: 30px;\n
\t\t\tline-height: 28px;\n
\t\t\tpadding: 0 12px 2px;\n
\t\t}\n
\n
\t\t.button:hover,\n
\t\t.button:focus {\n
\t\t\tbackground: #fafafa;\n
\t\t\tborder-color: #999;\n
\t\t\tcolor: #23282d;\n
\t\t}\n
\n
\t\t.button:focus  {\n
\t\t\tborder-color: #5b9dd9;\n
\t\t\t-webkit-box-shadow: 0 0 3px rgba( 0, 115, 170, .8 );\n
\t\t\tbox-shadow: 0 0 3px rgba( 0, 115, 170, .8 );\n
\t\t\toutline: none;\n
\t\t}\n
\n
\t\t.button:active {\n
\t\t\tbackground: #eee;\n
\t\t\tborder-color: #999;\n
\t\t \t-webkit-box-shadow: inset 0 2px 5px -3px rgba( 0, 0, 0, 0.5 );\n
\t\t \tbox-shadow: inset 0 2px 5px -3px rgba( 0, 0, 0, 0.5 );\n
\t\t \t-webkit-transform: translateY(1px);\n
\t\t \t-ms-transform: translateY(1px);\n
\t\t \ttransform: translateY(1px);\n
\t\t}\n
\n
\t\t\t</style>\n
</head>\n
<body id="error-page">\n
\t<p><strong>ERROR:</strong> Sorry, there was an error. Please be sure JavaScript and Cookies are enabled in your browser and try again.<br /><br />\n
\n
</p></body>\n
</html>\n
"""

**Comment by jamjon3** [comment]
OK. I have this figured out. WP-SpamShield blocks post requests. I had to disable that plugin. It appears it's not in good graces with the WordPress folks. I'll have to find an alternative or see if I can get a path exception (it has a whitelist .... which I can work with but a path is probably better... especially for dev puroposes).

Probably useful to document in a FAQ or in the readme but I'm going to just move forward. Thank you for you help on this!

**Comment by leanwebstart** [comment]
Pleasure...
